Team meeting minutes
speaking-portal-project-team-a/The-Speaking-Portal-Project pull request #41
Opened 2022-10-13 23:13 UTC by edouarde1

closes #36

2022-10-14 22:23 UTC, vnajack commented on docs/meetings/team/2022_10_11.md
> +
Also, Logan will be unavailable on Nov. 1 for medical reasons

2022-10-14 22:27 UTC, vnajack requested changes
just some spell checking!

2022-10-14 22:27 UTC, vnajack commented on docs/meetings/team/2022_10_11.md
> +- We did well on our presentation, Naziem was appricative
Spell check
```suggestion
- We did well on our presentation, Nazim was appreciative
```

2022-10-14 22:27 UTC, vnajack commented on docs/meetings/team/2022_10_11.md
> +- Need to contact Naziem for access
```suggestion
- Need to contact Nazim for access
```

2022-10-14 22:27 UTC, vnajack commented on docs/meetings/team/2022_10_11.md
> +- May be recorded while presenting in-class
Since we didn't record ourselves in class, we will need to make sure we get this done today. Will discuss after client meeting

2022-10-15 02:31 UTC, LoganParker approved these changes
All looks great!! Thank you for doing these, hopefully we can get them merged soon.

2022-10-15 04:55 UTC, vnajack approved these changes
Excellent, thank you for taking notes and making the updates!

2022-10-15 06:15 UTC, vnajack commented
Per Edouard in the Discord channel, I'm merging the branch on his behalf

2022-10-15 06:15 UTC, merged