testing strat report section
speaking-portal-project-team-a/The-Speaking-Portal-Project pull request #70
Opened 2022-10-21 01:10 UTC by edouarde1

closes #24 and #55

2022-10-21 02:40 UTC, LoganParker commented on docs/reports/requirements/6_test-strat.md
> +Unit tests will be built for each newly developed feature. Test scripts will be built and run using the Jest framework for Node.js and TypeScript. Within each testing script, features will be broken
Looks good! But remember the 120 character limit for Markdown!!

2022-10-21 16:32 UTC, LoganParker approved these changes
These look really good! thank you :)

2022-10-21 17:24 UTC, vnajack requested changes
Very clear and concise! Added a couple small suggestions. Thank you

2022-10-21 17:24 UTC, vnajack commented on docs/reports/requirements/6_test-strat.md
> +Continuous integration will be implemented using the CI/CD GitHub workflows. These workflows will be built to run tests and builds in a Node.Js environment. Initial CI testing will be focused on test
```suggestion
Continuous integration will be implemented using the CI/CD GitHub workflows. These workflows will be built to run tests and builds in a Node.Js environment. Initial CI testing will be focused on testing Node.Js package builds and will be ensuring all new package dependencies are accounted for in new code changes. These workflows will be triggered during each new pull request. If the tests fail, then the PR will need to be re-polished. If these tests pass, then new code can be merged into our repository. We may be integrating a framework called ‘SonarCloud’ which performs automated testing and code checking, although this software may require a fee. Continuous integration workflows will be frequently updated to ensure testing scripts are up-to-date.
```

2022-10-21 17:24 UTC, vnajack commented on docs/reports/requirements/6_test-strat.md
> +This project also requires an API build which will require separate testing to ensure that our product integrates with the client’s system. Postman will be the framework used to build and run tests f
```suggestion
This project also requires an API build which will require separate testing to ensure that our product integrates with the client’s system. Postman will be the framework used to build and run tests for our API. This framework allows mock client requests to be made directly to our API, and it ensures that our API is delivering contents correctly.
```

2022-10-21 17:47 UTC, vnajack approved these changes
Thank you so much! Looks great

2022-10-22 02:20 UTC, mkuelker approved these changes
Looks good

2022-10-22 04:27 UTC, vnajack commented
Merging on behalf of Edouard - he's out of town, so was unable to merge tonight

2022-10-22 04:27 UTC, merged