Team meeting minutes
speaking-portal-project-team-a/The-Speaking-Portal-Project pull request #80
Opened 2022-10-25 18:02 UTC by edouarde1

#79

2022-10-25 23:19 UTC, vnajack requested changes
Minor changes requested to clarify a few things. Thank you for taking the notes! We were going through a lot of info today to get our issues laid out, so having them quickly typed here helped a lot!

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_18.md
> +**Location**
```suggestion
**Location** Discord
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_18.md
> +**End Time**
I think we ended late last week, but I can't remember

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- Dad joke of the day
Why didn't the skeleton go Trick or Treating?
Because it didn't have any guts

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- Gannt Chart (this week)
```suggestion
- Gantt Chart (this week)
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- We should be better at planning
Planning ahead will be a bit now that requirements gathering is complete and development begins

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +#### Rubard
```suggestion
#### Rhubarb
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- Rubard Integration into Node.Js environment (Exploration)
```suggestion
- Rhubarb Integration into Node.Js environment (Exploration)
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- Integrate Rubarb into environment (Task)
```suggestion
- Integrate Rhubarb into environment (Task)
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +- Client IP Agreement signed (Task)
```suggestion
- Client IP Agreement - re-sign tomorrow in class (Task)
```

2022-10-25 23:19 UTC, vnajack commented on docs/meetings/team/2022_10_25.md
> +
```suggestion
- Client meeting cancelled this week & client is already informed and confirmed

```

2022-10-28 17:18 UTC, LoganParker approved these changes
These look great! Thanks a ton for taking these notes!

2022-10-28 21:39 UTC, vnajack approved these changes
Looks great, thank you for taking minutes!

2022-10-28 21:39 UTC, mkuelker approved these changes
Looks good

2022-10-29 00:12 UTC, merged